clear; close all; clc;
% Subject-specific data [length mass CM_loc(distal JC) MOI]
% Actual body mass 88.6 kg (when measured) 91.1 kg (when running)
% Foot:  [0.139 1.147 0.076 0.0059] - rear foot only
% Foot2: [0.224 1.385 0.142 0.0096] - combined 
% Shank: [0.453 5.271 0.261 0.0792]
% Thigh: [0.447 12.54 0.258 0.2122]
% UpArm: [0.323 3.162 0.185 0.0588]
% LwArm: [0.469 1.855 0.301 0.0568]
% Head+trunk: [0.869 40.90 0.427 1.4890] - CM_loc from proximal
%
% l1 = 0.418; m1 = 24.433; d1 = 0.323; I1 = 0.5218; % Lower trunk 
% l2 = 0.182; m2 = 10.860; d2 = 0.085; I2 = 0.0701; % Upper trunk
% l3 = 0.269; m3 = 5.6110; d3 = 0.136; I3 = 0.0344; % Head + neck
% 
% lT = l1 + l2 + l3;
% mT = m1 + m2 + m3;
% dT = 1/mT * (m1*d1 + m2*(l1+d2) + m3*(l1+l2+d3));   % From proximal end
% r1 = dT - d1; r2 = dT - (l1+d2); r3 = dT - (l1+l2+d3);
% IT = I1 + m1*r1^2 + I2 + m2*r2^2 + I3 + m3*r3^2;
%
%% Import data
p = [pwd '\Vicon\Vicon files\'];
f = 'run9_7_TM.c3d';
data = readC3D([p f]);
points = data.Markers.Data ./ 1000;     % In metres
pnames = data.Markers.Names;

%% COM
% Feet COM
RFootCM = points(:,:,strcmp(pnames,'R_Toe')) + ...
    (points(:,:,strcmp(pnames,'RAJC')) - points(:,:,strcmp(pnames,'R_Toe'))) .* (.142/.224);
LFootCM = points(:,:,strcmp(pnames,'L_Toe')) + ...
    (points(:,:,strcmp(pnames,'LAJC')) - points(:,:,strcmp(pnames,'L_Toe'))) .* (.142/.224);

% Shank COM
RShankCM = points(:,:,strcmp(pnames,'RAJC')) + ...
    (points(:,:,strcmp(pnames,'RKJC')) - points(:,:,strcmp(pnames,'RAJC'))) .* (.261/.453);
LShankCM = points(:,:,strcmp(pnames,'LAJC')) + ...
    (points(:,:,strcmp(pnames,'LKJC')) - points(:,:,strcmp(pnames,'LAJC'))) .* (.261/.453);

% Thigh COM
RThighCM = points(:,:,strcmp(pnames,'RKJC')) + ...
    (points(:,:,strcmp(pnames,'RHJC')) - points(:,:,strcmp(pnames,'RKJC'))) .* (.258/.447);
LThighCM = points(:,:,strcmp(pnames,'LKJC')) + ...
    (points(:,:,strcmp(pnames,'LHJC')) - points(:,:,strcmp(pnames,'LKJC'))) .* (.258/.447);

% Upper arm COM
RUpArmCM = points(:,:,strcmp(pnames,'REJC')) + ...
    (points(:,:,strcmp(pnames,'RSJC')) - points(:,:,strcmp(pnames,'REJC'))) .* (.185/.323);
LUpArmCM = points(:,:,strcmp(pnames,'LEJC')) + ...
    (points(:,:,strcmp(pnames,'LSJC')) - points(:,:,strcmp(pnames,'LEJC'))) .* (.185/.323);

% Lower arm COM
RLwArmCM = points(:,:,strcmp(pnames,'RWJC')) + ...
    (points(:,:,strcmp(pnames,'REJC')) - points(:,:,strcmp(pnames,'RWJC'))) .* (.301/.469);
LLwArmCM = points(:,:,strcmp(pnames,'LWJC')) + ...
    (points(:,:,strcmp(pnames,'LEJC')) - points(:,:,strcmp(pnames,'LWJC'))) .* (.301/.469);

% % Head+trunk COM
% HJC = (points(:,:,strcmp(pnames,'RHJC')) + points(:,:,strcmp(pnames,'LHJC'))) / 2;
% SJC = (points(:,:,strcmp(pnames,'RSJC')) + points(:,:,strcmp(pnames,'LSJC'))) / 2;
% head = (points(:,:,strcmp(pnames,'HeadRF')) + ...
%         points(:,:,strcmp(pnames,'HeadLF')) + ...
%         points(:,:,strcmp(pnames,'HeadRB')) + ...
%         points(:,:,strcmp(pnames,'HeadLB'))) /4;
% 
% HATCM = HJC + (head - HJC) .* (0.427/0.869);
% 
% % Whole body COM
% WBCM = RFootCM.*(1.147/91.1) + RShankCM.*(5.271/91.1) + RThighCM.*(12.54/91.1) + ...
%        LFootCM.*(1.147/91.1) + LShankCM.*(5.271/91.1) + LThighCM.*(12.54/91.1) + ...
%        RUpArmCM.*(3.162/91.1) + RLwArmCM.*(1.855/91.1) + ...
%        LUpArmCM.*(3.162/91.1) + LLwArmCM.*(1.855/91.1) + ...
%        HATCM.*(40.90/91.1);

% Lower trunk CoM

%% Plot
set(figure(1),'WindowStyle','docked')
hold on
xlim([-0.9 0.9]); ylim([-0.3 1.5]); zlim([-0.1 1.7])
set(gca,'xtick',[]); set(gca,'ytick',[]); set(gca,'ztick',[])
view([123 8])
for i = 1:12:length(WBCM)
    cla
    hold on
% Right leg
    line([points(i,1,strcmp(pnames,'RHJC')) ...
          points(i,1,strcmp(pnames,'RKJC')) ...
          points(i,1,strcmp(pnames,'RAJC')) ...
          points(i,1,strcmp(pnames,'R_Toe'))],...
         [points(i,2,strcmp(pnames,'RHJC')) ...
          points(i,2,strcmp(pnames,'RKJC')) ...
          points(i,2,strcmp(pnames,'RAJC')) ...
          points(i,2,strcmp(pnames,'R_Toe'))],...
         [points(i,3,strcmp(pnames,'RHJC')) ...
          points(i,3,strcmp(pnames,'RKJC')) ...
          points(i,3,strcmp(pnames,'RAJC')) ...
          points(i,3,strcmp(pnames,'R_Toe'))])       
% Left leg
    line([points(i,1,strcmp(pnames,'LHJC')) ...
          points(i,1,strcmp(pnames,'LKJC')) ...
          points(i,1,strcmp(pnames,'LAJC')) ...
          points(i,1,strcmp(pnames,'L_Toe'))],...
         [points(i,2,strcmp(pnames,'LHJC')) ...
          points(i,2,strcmp(pnames,'LKJC')) ...
          points(i,2,strcmp(pnames,'LAJC')) ...
          points(i,2,strcmp(pnames,'L_Toe'))],...
         [points(i,3,strcmp(pnames,'LHJC')) ...
          points(i,3,strcmp(pnames,'LKJC')) ...
          points(i,3,strcmp(pnames,'LAJC')) ...
          points(i,3,strcmp(pnames,'L_Toe'))])             
% Right arm
    line([points(i,1,strcmp(pnames,'RSJC')) ...
          points(i,1,strcmp(pnames,'REJC')) ...
          points(i,1,strcmp(pnames,'RWJC'))], ...
         [points(i,2,strcmp(pnames,'RSJC')) ...
          points(i,2,strcmp(pnames,'REJC')) ...
          points(i,2,strcmp(pnames,'RWJC'))], ...
         [points(i,3,strcmp(pnames,'RSJC')) ...
          points(i,3,strcmp(pnames,'REJC')) ...
          points(i,3,strcmp(pnames,'RWJC'))]) ...
% Left arm
    line([points(i,1,strcmp(pnames,'LSJC')) ...
          points(i,1,strcmp(pnames,'LEJC')) ...
          points(i,1,strcmp(pnames,'LWJC'))], ...
         [points(i,2,strcmp(pnames,'LSJC')) ...
          points(i,2,strcmp(pnames,'LEJC')) ...
          points(i,2,strcmp(pnames,'LWJC'))], ...
         [points(i,3,strcmp(pnames,'LSJC')) ...
          points(i,3,strcmp(pnames,'LEJC')) ...
          points(i,3,strcmp(pnames,'LWJC'))]) ...
% Trunk + pelvis
    line([points(i,1,strcmp(pnames,'RSJC')) ...
          points(i,1,strcmp(pnames,'LSJC')) ...
          HJC(i,1),...
          points(i,1,strcmp(pnames,'RSJC'))], ...
         [points(i,2,strcmp(pnames,'RSJC')) ...
          points(i,2,strcmp(pnames,'LSJC')) ...
          HJC(i,2),...
          points(i,2,strcmp(pnames,'RSJC'))], ...
         [points(i,3,strcmp(pnames,'RSJC')) ...
          points(i,3,strcmp(pnames,'LSJC')) ...
          HJC(i,3),...
          points(i,3,strcmp(pnames,'RSJC'))]), ...
    line([points(i,1,strcmp(pnames,'RHJC')) ...
          points(i,1,strcmp(pnames,'LHJC'))], ...
         [points(i,2,strcmp(pnames,'RHJC')) ...
          points(i,2,strcmp(pnames,'LHJC'))], ...
         [points(i,3,strcmp(pnames,'RHJC')) ...
          points(i,3,strcmp(pnames,'LHJC'))]), ...
          
% Head
    line([SJC(i,1) head(i,1)],...
         [SJC(i,2) head(i,2)],...
         [SJC(i,3) head(i,3)])
    
% Force plate
    line([points(i,1,strcmp(pnames,'Treadmill_FL')) ...
          points(i,1,strcmp(pnames,'Treadmill_FR')) ...
          points(i,1,strcmp(pnames,'Treadmill_BR')) ...
          points(i,1,strcmp(pnames,'Treadmill_BL')) ...
          points(i,1,strcmp(pnames,'Treadmill_FL'))], ...
         [points(i,2,strcmp(pnames,'Treadmill_FL')) ...
          points(i,2,strcmp(pnames,'Treadmill_FR')) ...
          points(i,2,strcmp(pnames,'Treadmill_BR')) ...
          points(i,2,strcmp(pnames,'Treadmill_BL')) ...
          points(i,2,strcmp(pnames,'Treadmill_FL'))], ...         
         [points(i,3,strcmp(pnames,'Treadmill_FL')) ...
          points(i,3,strcmp(pnames,'Treadmill_FR')) ...
          points(i,3,strcmp(pnames,'Treadmill_BR')) ...
          points(i,3,strcmp(pnames,'Treadmill_BL')) ...
          points(i,3,strcmp(pnames,'Treadmill_FL'))])
            
% Whole body COM
    plot3(WBCM(i,1),WBCM(i,2),WBCM(i,3), 'ko')
     drawnow
     
end
          
%% Output
WBCMv = tr_diff(WBCM, 0.004);
save('CM_unfiltered9_7', 'WBCM', 'WBCMv')
      
% Trunk+head CM relative to hip joint
l7R = HATCM - points(:,:,strcmp(pnames, 'RHJC'));
l7L = HATCM - points(:,:,strcmp(pnames, 'LHJC'));